version: '3'
services:
  db:
    image: postgres
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "2345:5432"